name: Build CLI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: git-sha-short
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.13

      - name: build
        run: earthly --ci +build-release

      - run: ls -la dist

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            dist/restake-authz-ledger-darwin-amd64.tar.gz
            dist/restake-authz-ledger-darwin-arm64.tar.gz
            dist/restake-authz-ledger-linux-amd64.tar.gz
            dist/restake-authz-ledger-linux-arm64.tar.gz
            dist/restake-authz-ledger-windows-amd64.tar.gz
            dist/restake-authz-ledger-windows-arm64.tar.gz
